version: '3.4'

services:
  catalogdb:
    image: mongo
    
  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  orderdb:
    image: msmsqladvntr

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  rabbitmq:
    image: rabbitmq:3-management-alpine

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket.API/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
    dockerfile: Services/Ordering/Ordering.API/Dockerfile
  
  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateways/Shopping.Aggregator/Dockerfile
      
volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data:

